### ISSUE TITLE
Tests: asynchronous and parallelism

### ISSUE THREAD

**Issue by kuraga** [thunks/tman#9]
Hello, @zensh ! New question.

As I see "asynchronous test" means two things:

1. Test is done not on `return` but `done` callback called.
2. Asynchronous tests might be called in parallel.

Is there some option to make 1 without 2?

Thanks!

**Comment by zensh** [comment]
Could you give some example?

**Comment by kuraga** [comment]
Oh, it was my fault. Tests are not executed in parallel. I'm sorry.

But @zensh , could you, please, comment my issue in [https://github.com/zensh/route-trie](route-trie)? Tghanks.
